const modelData = [
    {
        "model": "Gemini-1.5-Pro-Exp-0801",
        "provider": "Google AI",
        "smartsElo": 1305, // Updated to Gemini-1.5-Pro-002 value
        "codingElo": 1287,
        "speed": 52,
        "context": 2000,
        "inputPrice": 3.5,
        "outputPrice": 10.5,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": "these prices are for <128k context, for more see pricing page, no free tier in EU"
    },
    {
        "model": "gpt-4o-2024-08-06",
        "provider": "openAI",
        "smartsElo": 1339, // Updated to ChatGPT-4o-latest value
        "codingElo": 1338,
        "speed": 69,
        "context": 128,
        "inputPrice": 2.5,
        "outputPrice": 10,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": "can be 50% cheaper using batch processing"
    },
    {
        "model": "GPT-4o-mini-2024-07-18",
        "provider": "openAI",
        "smartsElo": 1274,
        "codingElo": 1284,
        "speed": null,
        "context": 128,
        "inputPrice": 0.15,
        "outputPrice": 0.6,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "Claude 3.5 Sonnet",
        "provider": "anthropic",
        "smartsElo": 1268,
        "codingElo": 1295,
        "speed": null,
        "context": 200,
        "inputPrice": 3,
        "outputPrice": 15,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "gpt-4-turbo-2024-04-09",
        "provider": "openAI",
        "smartsElo": 1250, // Updated to GPT-4-1106-preview value
        "codingElo": 1254,
        "speed": 17,
        "context": 128,
        "inputPrice": 10,
        "outputPrice": 30,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": "can be 50% cheaper using batch processing"
    },
    {
        "model": "Claude 3 Opus",
        "provider": "anthropic",
        "smartsElo": 1248,
        "codingElo": 1250,
        "speed": 26,
        "context": 200,
        "inputPrice": 15,
        "outputPrice": 75,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "llama-3-70b-instruct",
        "provider": "Groq",
        "smartsElo": 1206,
        "codingElo": 1200,
        "speed": 280,
        "context": 8,
        "inputPrice": 0.59,
        "outputPrice": 0.79,
        "hasVision": false,
        "hasFreeTier": true,
        "notes": "free tier, subject to 7k t/min limit"
    },
    {
        "model": "llama-3-70b-instruct",
        "provider": "together.ai",
        "smartsElo": 1206,
        "codingElo": 1200,
        "speed": 52,
        "context": 8,
        "inputPrice": 0.9,
        "outputPrice": 0.9,
        "hasVision": false,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "Claude 3 Sonnet",
        "provider": "anthropic",
        "smartsElo": 1201,
        "codingElo": 1213,
        "speed": 59,
        "context": 200,
        "inputPrice": 3,
        "outputPrice": 15,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "Command R+",
        "provider": "Cohere",
        "smartsElo": 1214,
        "codingElo": 1180,
        "speed": 109,
        "context": 128,
        "inputPrice": 3,
        "outputPrice": 15,
        "hasVision": false,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "Reka-Core",
        "provider": "Reka AI",
        "smartsElo": 1230,
        "codingElo": 1208,
        "speed": null,
        "context": 128,
        "inputPrice": 10,
        "outputPrice": 25,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "Claude 3 Haiku",
        "provider": "anthropic",
        "smartsElo": 1179,
        "codingElo": 1189,
        "speed": 89,
        "context": 200,
        "inputPrice": 0.25,
        "outputPrice": 1.25,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "Gemini 1.5 Flash",
        "provider": "Google AI",
        "smartsElo": 1269, // Updated to Gemini-1.5-Flash-002 value
        "codingElo": 1249,
        "speed": 156,
        "context": 1000,
        "inputPrice": 0.35,
        "outputPrice": 0.53,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": "these prices are for <128k context, for more see pricing page, no free tier in EU"
    },
    {
        "model": "llama-3-8b-instruct",
        "provider": "Groq",
        "smartsElo": 1152,
        "codingElo": 1146,
        "speed": 870,
        "context": 8,
        "inputPrice": 0.05,
        "outputPrice": 0.1,
        "hasVision": false,
        "hasFreeTier": true,
        "notes": "free tier, subject to 15k t/min limit"
    },
    {
        "model": "llama-3-8b-instruct",
        "provider": "cloudflare",
        "smartsElo": 1152,
        "codingElo": 1146,
        "speed": 215,
        "context": 8,
        "inputPrice": 0,
        "outputPrice": 0,
        "hasVision": false,
        "hasFreeTier": true,
        "notes": "currently in free beta"
    },
    {
        "model": "Llama-3.1-8b-Instruct",
        "provider": "Groq",
        "smartsElo": 1173,
        "codingElo": 1182,
        "speed": null,
        "context": 128,
        "inputPrice": 0,
        "outputPrice": 0,
        "hasVision": false,
        "hasFreeTier": true,
        "notes": "free tier, subject to 121k t/min limit"
    },
    {
        "model": "Phi-3-medium",
        "provider": "Azure AI",
        "smartsElo": 1123,
        "codingElo": 1125,
        "speed": null,
        "context": 128,
        "inputPrice": 0.5,
        "outputPrice": 1.5,
        "hasVision": false,
        "hasFreeTier": false,
        "notes": "There's also Phi-3-vision but it's not yet on Model-as-a-Service offering"
    },
    {
        "model": "gpt-3.5-turbo-0125",
        "provider": "openAI",
        "smartsElo": 1106,
        "codingElo": 1124,
        "speed": 56,
        "context": 16,
        "inputPrice": 0.5,
        "outputPrice": 1.5,
        "hasVision": false,
        "hasFreeTier": false,
        "notes": ""
    }
];
