const modelData = [
    {
        "model": "Gemini-1.5-Pro-Exp-0801",
        "provider": "Google AI",
        "smartsElo": 1299,
        "codingElo": 1274,
        "speed": 52,
        "context": 2000,
        "inputPrice": 3.5,
        "outputPrice": 10.5,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": "these prices are for <128k context, for more see pricing page, no free tier in EU"
    },
    {
        "model": "gpt-4o-2024-08-06",
        "provider": "openAI",
        "smartsElo": 1287,
        "codingElo": 1296,
        "speed": 69,
        "context": 128,
        "inputPrice": 2.5,
        "outputPrice": 10,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": "can be 50% cheaper using batch processing"
    },
    {
        "model": "GPT-4o-mini-2024-07-18",
        "provider": "openAI",
        "smartsElo": 1277,
        "codingElo": 1283,
        "speed": null,
        "context": 128,
        "inputPrice": 0.15,
        "outputPrice": 0.6,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "Claude 3.5 Sonnet",
        "provider": "anthropic",
        "smartsElo": 1271,
        "codingElo": 1302,
        "speed": null,
        "context": 200,
        "inputPrice": 3,
        "outputPrice": 15,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "gpt-4-turbo-2024-04-09",
        "provider": "openAI",
        "smartsElo": 1258,
        "codingElo": 1266,
        "speed": 17,
        "context": 128,
        "inputPrice": 10,
        "outputPrice": 30,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": "can be 50% cheaper using batch processing"
    },
    {
        "model": "Claude 3 Opus",
        "provider": "anthropic",
        "smartsElo": 1248,
        "codingElo": 1251,
        "speed": 26,
        "context": 200,
        "inputPrice": 15,
        "outputPrice": 75,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "llama-3-70b-instruct",
        "provider": "Groq",
        "smartsElo": 1208,
        "codingElo": 1201,
        "speed": 280,
        "context": 8,
        "inputPrice": 0.59,
        "outputPrice": 0.79,
        "hasVision": false,
        "hasFreeTier": true,
        "notes": "free tier, subject to 7k t/min limit"
    },
    {
        "model": "llama-3-70b-instruct",
        "provider": "together.ai",
        "smartsElo": 1208,
        "codingElo": 1201,
        "speed": 52,
        "context": 8,
        "inputPrice": 0.9,
        "outputPrice": 0.9,
        "hasVision": false,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "Claude 3 Sonnet",
        "provider": "anthropic",
        "smartsElo": 1200,
        "codingElo": 1215,
        "speed": 59,
        "context": 200,
        "inputPrice": 3,
        "outputPrice": 15,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "Command R+",
        "provider": "Cohere",
        "smartsElo": 1189,
        "codingElo": 1167,
        "speed": 109,
        "context": 128,
        "inputPrice": 3,
        "outputPrice": 15,
        "hasVision": false,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "Reka-Core",
        "provider": "Reka AI",
        "smartsElo": 1199,
        "codingElo": 1193,
        "speed": null,
        "context": 128,
        "inputPrice": 10,
        "outputPrice": 25,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "Claude 3 Haiku",
        "provider": "anthropic",
        "smartsElo": 1180,
        "codingElo": 1191,
        "speed": 89,
        "context": 200,
        "inputPrice": 0.25,
        "outputPrice": 1.25,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "Gemini 1.5 Flash",
        "provider": "Google AI",
        "smartsElo": 1160,
        "codingElo": null,
        "speed": 156,
        "context": 1000,
        "inputPrice": 0.35,
        "outputPrice": 0.53,
        "hasVision": true,
        "hasFreeTier": false,
        "notes": "these prices are for <128k context, for more see pricing page, no free tier in EU"
    },
    {
        "model": "llama-3-8b-instruct",
        "provider": "Groq",
        "smartsElo": 1154,
        "codingElo": 1147,
        "speed": 870,
        "context": 8,
        "inputPrice": 0.05,
        "outputPrice": 0.1,
        "hasVision": false,
        "hasFreeTier": true,
        "notes": "free tier, subject to 15k t/min limit"
    },
    {
        "model": "llama-3-8b-instruct",
        "provider": "cloudflare",
        "smartsElo": 1154,
        "codingElo": 1147,
        "speed": 215,
        "context": 8,
        "inputPrice": 0,
        "outputPrice": 0,
        "hasVision": false,
        "hasFreeTier": true,
        "notes": "currently in free beta"
    },
    {
        "model": "Llama-3.1-8b-Instruct",
        "provider": "Groq",
        "smartsElo": 1152,
        "codingElo": null,
        "speed": null,
        "context": 128,
        "inputPrice": 0,
        "outputPrice": 0,
        "hasVision": false,
        "hasFreeTier": true,
        "notes": "free tier, subject to 121k t/min limit"
    },
    {
        "model": "Phi-3-medium",
        "provider": "Azure AI",
        "smartsElo": 1120,
        "codingElo": null,
        "speed": null,
        "context": 128,
        "inputPrice": 0.5,
        "outputPrice": 1.5,
        "hasVision": false,
        "hasFreeTier": false,
        "notes": "There's also Phi-3-vision but it's not yet on Model-as-a-Service offering"
    },
    {
        "model": "gpt-3.5-turbo-0125",
        "provider": "openAI",
        "smartsElo": 1109,
        "codingElo": 1137,
        "speed": 56,
        "context": 16,
        "inputPrice": 0.5,
        "outputPrice": 1.5,
        "hasVision": false,
        "hasFreeTier": false,
        "notes": ""
    },
    {
        "model": "StarCoder 7B",
        "provider": "fireworks.ai",
        "smartsElo": null,
        "codingElo": null,
        "speed": null,
        "context": 8,
        "inputPrice": 0.2,
        "outputPrice": 0.2,
        "hasVision": false,
        "hasFreeTier": true,
        "notes": "fill-in-the-middle model, good for code autocomplete"
    }
];
